name: knotwork
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  dio: ^5.8.0+1
  file_picker: ^10.1.2
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  transparent_image: ^2.0.0
  flutter_markdown: ^0.7.6+2
  flutter_masked_text2: ^0.9.1
  flutter_secure_storage: ^9.2.4
  image_picker: ^1.1.2
  # local_auth: ^2.3.0
  otp: ^3.1.4
  passkeys: ^2.7.1
  # webauthn: ^0.2.5
  passkeys_android: ^2.7.0
  provider: ^6.1.2
  shared_preferences: ^2.5.2
  web_socket_channel: ^3.0.2
  webview_all: ^0.5.2
  mapbox_maps_flutter: ^2.0.0
  flutter_speed_dial: ^7.0.0
  webview_flutter: ^4.13.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
  - assets/policies/policies.md
  - assets/images/
  - assets/.env
  - assets/web/cytoscape.min.js
  - assets/web/graph.html